# Generated by Django 3.2.23 on 2024-03-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=20)),
                ('disease_symptom', models.CharField(max_length=200)),
                ('disease_image', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'disease',
                'managed': False,
            },
        ),
    ]
